import { library } from '@fortawesome/fontawesome-svg-core';
import { FontAwesomeIcon, FontAwesomeLayers } from '@fortawesome/vue-fontawesome';

// Solid Icons
import {
  faChartBar,
  faPlus,
  faHistory,
  faMobileAlt,
  faCode,
  faCog,
  faSignOutAlt,
  faQuoteRight,
  faTrash,
  faEye,
  faRobot,
  faClock,
  faHashtag,
  faComments,
  faCheckCircle,
  faTimesCircle,
  faUser,
  faMapMarkerAlt,
  faCogs,
  faPencil,
  faSave,
  faTimes,
  faPaperPlane,
  faRedo,
  faArrowLeft,
  faCopy,
  faEnvelope,
  faCheck,
  faDollarSign,
  faSearch,
  faBolt,
  faPhone,
  faCommentDots,
  faChartLine,
  faUsers,
  faShieldAlt,
  faEnvelopeOpen,
  faEyeSlash,
  faSignInAlt,
  faStar,
  faSpinner,
  faLock,
  faArrowRight,
  faBuilding,
  faCreditCard,
  faRocket,
  faTachometerAlt,
  faForward,
  faCrown,
  faHeadset,
  faBook,
  faDownload,
  faExternalLinkAlt,
  faExclamationTriangle,
  faFileInvoice,
  faTrophy,
  faBrain,
  faBoltLightning,
  faStopwatch,
  faPiggyBank,
  faSadTear,
  faWandSparkles,
  faKey,
  faLockOpen,
  faVoicemail,
  faPhoneVolume,
  faPhoneSlash,
  faPercentage,
  faInbox,
  faPhoneAlt,
  faRoute,
  faFileText,
  faClipboardList,
  faBars,
  faArrowDown,
  faReply,
  faPlay,
  faUserTie,
  faUtensils,
  faUserTimes,
  faCalculator,
  faPause,
  faFlag,
  faUndo,
  faInfoCircle,
  faMoneyBillWave,
  faMagic,
  faQuestionCircle,
  faLightbulb,
} from '@fortawesome/free-solid-svg-icons';

// Regular Icons
//import { } from '@fortawesome/free-regular-svg-icons';

// Svg Icons
// import {} from '@fortawesome/free-brands-svg-icons';

library.add(
  faChartBar,
  faPlus,
  faHistory,
  faMobileAlt,
  faCode,
  faCog,
  faSignOutAlt,
  faQuoteRight,
  faTrash,
  faEye,
  faRobot,
  faClock,
  faHashtag,
  faComments,
  faCheckCircle,
  faTimesCircle,
  faUser,
  faMapMarkerAlt,
  faCogs,
  faPencil,
  faSave,
  faTimes,
  faPaperPlane,
  faRedo,
  faArrowLeft,
  faCopy,
  faEnvelope,
  faCheck,
  faDollarSign,
  faSearch,
  faBolt,
  faPhone,
  faCommentDots,
  faChartLine,
  faUsers,
  faShieldAlt,
  faEnvelopeOpen,
  faEyeSlash,
  faSignInAlt,
  faStar,
  faSpinner,
  faLock,
  faArrowRight,
  faBuilding,
  faCreditCard,
  faRocket,
  faTachometerAlt,
  faForward,
  faCrown,
  faHeadset,
  faBook,
  faDownload,
  faExternalLinkAlt,
  faFileInvoice,
  faExclamationTriangle,
  faTrophy,
  faBrain,
  faBoltLightning,
  faStopwatch,
  faPiggyBank,
  faSadTear,
  faWandSparkles,
  faKey,
  faLockOpen,
  faVoicemail,
  faPhoneVolume,
  faPhoneSlash,
  faPercentage,
  faInbox,
  faPhoneAlt,
  faRoute,
  faFileText,
  faClipboardList,
  faBars,
  faArrowDown,
  faReply,
  faPlay,
  faUserTie,
  faUtensils,
  faUserTimes,
  faCalculator,
  faPause,
  faFlag,
  faUndo,
  faInfoCircle,
  faMoneyBillWave,
  faMagic,
  faQuestionCircle,
  faLightbulb,
);

export default function SetupFontAwesome(app) {
  /**
   * Register our FontAwesome component
   * https://github.com/FortAwesome/vue-fontawesome
   */
  app.component('font-awesome-icon', FontAwesomeIcon);
  app.component('font-awesome-layers', FontAwesomeLayers);
  return app;
}
