name: Deploy to Production

on:
    push:
        branches:
            - main

jobs:
    deploy:
        name: Deploy to Vultr
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'

            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.4'
                  extensions: mbstring, bcmath, mysql

            - name: Install composer dependencies
              run: composer install --no-dev --optimize-autoloader

            - name: Deploy to server
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.VULTR_HOST }}
                  username: ${{ secrets.VULTR_USER }}
                  key: ${{ secrets.VULTR_SSH_KEY }}
                  script: |
                      cd /var/www/pingmate
                      git pull origin main
                      composer install --no-dev --optimize-autoloader
                      php artisan migrate --force
                      
                      npm install
                      npm run build
                      
                      php artisan optimize:clear
                      php artisan config:cache
                      php artisan route:cache
                      php artisan view:cache
                      php artisan event:cache

                      sudo systemctl reload php8.4-fpm